version: '3.8'

services:
  vault:
    image:  hashicorp/vault:1.19.4
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    command: vault server -dev

  vault-init:
    image: hashicorp/vault:1.19.4
    depends_on:
      - vault
    volumes:
      - ./init-vault.sh:/init-vault.sh:ro
    entrypoint: /bin/sh
    command: -c "apk add --no-cache curl >/dev/null && sleep 2 && sh /init-vault.sh"

  app:
    build:
      context: .
    container_name: acme-platform
    depends_on:
      - vault-init
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_VAULT_URI: http://vault:8200
      SPRING_CLOUD_VAULT_TOKEN: root
    ports:
      - "8080:8080"
