version: '3.8'

services:
  postgres:
    image: postgres:16.6
    container_name: acme_pg_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: acmedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
  vault:
    image: hashicorp/vault:1.19.4
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    command: vault server -dev

  vault-init:
    image: hashicorp/vault:1.19.4
    depends_on:
      - vault
    volumes:
      - ./init-vault.sh:/init-vault.sh:ro
    tty: true
    stdin_open: true
    entrypoint: /bin/sh
    command: >
      -c "
      apk add --no-cache curl openssl >/dev/null &&
      echo 'curl and openssl installed' &&
      sh /init-vault.sh
      "

  app:
    build:
      context: .
    container_name: acme-platform
    depends_on:
      - vault-init
      - postgres
    environment:
      ACME_DB_HOST: postgres
      SPRING_CLOUD_VAULT_URI: http://vault:8200
      SPRING_CLOUD_VAULT_TOKEN: root
    ports:
      - "8080:8080"

volumes:
  postgres_data: