spring:
  application:
    name: acme-platform
  cloud:
    vault:
      uri: ${SPRING_CLOUD_VAULT_URI:http://vault:8200}
      token: ${SPRING_CLOUD_VAULT_TOKEN:root}
      kv:
        enabled: true
        backend: secret
      authentication: TOKEN
management:
  endpoints:
    web:
      exposure:
        include: "*"